/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Hussainberg.glb --types --transform --shadows --keepnames --meta --printwidth 120 
Files: public/models/Hussainberg.glb [986.86KB] > /home/abdas/Projects/threejs-intro/Hussainberg-transformed.glb [419.4KB] (58%)
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { SkeletonUtils } from 'three-stdlib'
import { useCharacterAnimations } from '../hooks/useCharacterAnimations'

type ActionName = 'Idel' | 'Run' | 'T-pose' | 'Walk' | 'WalkWoman'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Head: THREE.SkinnedMesh
    Ladonee: THREE.SkinnedMesh
    Nogi: THREE.SkinnedMesh
    Rookee: THREE.SkinnedMesh
    Tors: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    ['Material.020']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Hussainberg(props: React.JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF(import.meta.env.BASE_URL + 'models/Hussainberg-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)
  const { setAnimations, animationIndex } = useCharacterAnimations()

  useEffect(() => {
    setAnimations(names)
  }, [names, setAnimations])

  useEffect(() => {
    const action = actions[names[animationIndex]]
    action?.reset().fadeIn(0.5).play()

    return () => {
      action?.fadeOut(0.5)
    }
  }, [animationIndex, actions, names])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01} userData={{ name: 'Armature' }}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh
          name="Head"
          geometry={nodes.Head.geometry}
          material={materials['Material.020']}
          skeleton={nodes.Head.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          userData={{ name: 'Head' }}
          castShadow
        />
        <skinnedMesh
          name="Ladonee"
          geometry={nodes.Ladonee.geometry}
          material={materials['Material.020']}
          skeleton={nodes.Ladonee.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          userData={{ name: 'Ladonee' }}
          castShadow
        />
        <skinnedMesh
          name="Nogi"
          geometry={nodes.Nogi.geometry}
          material={materials['Material.020']}
          skeleton={nodes.Nogi.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          userData={{ name: 'Nogi' }}
          castShadow
        />
        <skinnedMesh
          name="Rookee"
          geometry={nodes.Rookee.geometry}
          material={materials['Material.020']}
          skeleton={nodes.Rookee.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          userData={{ name: 'Rookee' }}
          castShadow
        />
        <skinnedMesh
          name="Tors"
          geometry={nodes.Tors.geometry}
          material={materials['Material.020']}
          skeleton={nodes.Tors.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          userData={{ name: 'Tors' }}
          castShadow
        />
      </group>
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'models/Hussainberg-transformed.glb')
